services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - app1_net
      - app2_net
  app1:
    image: php:8.3.14-apache
    networks:
      - app1_net
    volumes:
      - "./app1:/var/www/html"
  app2:
    image: php:8.3.14-apache
    networks:
      - app2_net
    volumes:
      - "./app2:/var/www/html"

networks:
  app1_net:
  app2_net:
